import type { QuestionConfig, UserProfile } from './types';

export const questions: QuestionConfig[] = [
  {
    id: 'employmentStatus',
    emoji: '💼',
    title: 'What is your employment status?',
    type: 'choice',
    options: [
      { label: 'Full-time employed', description: 'Salaried or hourly, W-2 employee' },
      { label: 'Self-employed', description: 'Freelancer, contractor, or business owner' },
      { label: 'Part-time employed', description: 'Working less than full-time hours' },
      { label: 'Retired', description: 'On pension or retirement income' },
      { label: 'Currently not employed', description: 'Between jobs or not working' },
    ],
  },
  {
    id: 'employmentLength',
    emoji: '📅',
    title: 'How long have you been in your current job or field?',
    subtitle: 'Lenders typically look for 2+ years of employment history.',
    type: 'choice',
    options: [
      { label: 'Less than 1 year', description: 'Just started recently' },
      { label: '1–2 years', description: 'Building experience' },
      { label: '2–5 years', description: 'Well established' },
      { label: '5+ years', description: 'Long-term tenure' },
    ],
  },
  {
    id: 'annualIncome',
    emoji: '💰',
    title: 'What is your annual gross income?',
    subtitle: 'Your total income before taxes. Include all sources.',
    type: 'text',
    placeholder: 'e.g. 85000',
    prefix: '$',
  },
  {
    id: 'hasCoBorrower',
    emoji: '👥',
    title: 'Will you have a co-borrower?',
    subtitle: "A spouse or partner's income can increase your buying power.",
    type: 'choice',
    options: [
      { label: 'Yes', description: 'Applying jointly with another person' },
      { label: 'No', description: 'Applying on my own' },
    ],
  },
  {
    id: 'coBorrowerIncome',
    emoji: '💰',
    title: "What is your co-borrower's annual income?",
    subtitle: 'Their total income before taxes.',
    type: 'text',
    placeholder: 'e.g. 65000',
    prefix: '$',
    skipIf: (profile: UserProfile) => profile.hasCoBorrower !== 'Yes',
  },
  {
    id: 'creditScore',
    emoji: '📊',
    title: "What's your estimated credit score?",
    subtitle: "Don't worry if you're not sure — just pick your best guess.",
    type: 'choice',
    options: [
      { label: 'Excellent (750+)', description: 'Very few missed payments, low debt' },
      { label: 'Good (700–749)', description: 'Generally responsible with credit' },
      { label: 'Fair (650–699)', description: 'Some late payments or higher balances' },
      { label: 'Below 650', description: 'Significant credit challenges' },
      { label: "I'm not sure", description: "We'll work with a general estimate" },
    ],
  },
  {
    id: 'downPayment',
    emoji: '🏦',
    title: 'How much do you have saved for a down payment?',
    subtitle: 'Include savings, gifts, or grants you plan to use.',
    type: 'text',
    placeholder: 'e.g. 40000',
    prefix: '$',
  },
  {
    id: 'monthlyDebt',
    emoji: '🗂',
    title: 'What are your total monthly debt payments?',
    subtitle: 'Include car loans, student loans, credit cards, and other payments.',
    type: 'text',
    placeholder: 'e.g. 500',
    prefix: '$',
  },
  {
    id: 'bankruptcyForeclosure',
    emoji: '📁',
    title: 'Have you had a bankruptcy or foreclosure in the last 7 years?',
    type: 'choice',
    options: [
      { label: 'No', description: 'Clean record' },
      { label: 'Bankruptcy', description: 'Filed for bankruptcy' },
      { label: 'Foreclosure', description: 'Had a home foreclosed' },
      { label: 'Both', description: 'Experienced both events' },
    ],
  },
  {
    id: 'mortgageType',
    emoji: '🪵',
    title: 'What type of mortgage are you considering?',
    subtitle: 'Not sure? Conventional is the most common.',
    type: 'choice',
    options: [
      { label: 'Conventional', description: 'Standard loan, typically 5–20% down' },
      { label: 'FHA Loan', description: 'Government-backed, as low as 3.5% down' },
      { label: 'VA Loan', description: 'For veterans & active military, 0% down' },
      { label: 'USDA Loan', description: 'Rural areas, 0% down' },
      { label: 'Not sure yet', description: "We'll help you figure it out" },
    ],
  },
  {
    id: 'propertyUse',
    emoji: '🏠',
    title: 'How will you use the property?',
    subtitle: 'Lenders offer different rates depending on the intended use.',
    type: 'choice',
    options: [
      { label: 'Primary residence', description: 'My main home' },
      { label: 'Vacation / second home', description: 'A getaway or seasonal property' },
      { label: 'Investment / rental property', description: 'Income-generating real estate' },
    ],
  },
  {
    id: 'propertyType',
    emoji: '🏘',
    title: 'What type of property are you looking at?',
    type: 'choice',
    options: [
      { label: 'Single-family home', description: 'Standalone house' },
      { label: 'Condo / Townhouse', description: 'Shared-wall community' },
      { label: 'Multi-family (2–4 units)', description: 'Duplex, triplex, or fourplex' },
      { label: 'Not sure yet', description: 'Still exploring options' },
    ],
  },
  {
    id: 'state',
    emoji: '📍',
    title: 'What state are you looking to buy in?',
    subtitle: 'Home prices and loan limits vary significantly by location.',
    type: 'text',
    placeholder: 'e.g. Utah',
  },
  {
    id: 'firstTimeBuyer',
    emoji: '🔑',
    title: 'Is this your first home purchase?',
    subtitle: 'First-time buyers may qualify for special programs and grants.',
    type: 'choice',
    options: [
      { label: 'Yes, first-time buyer', description: 'Never owned a home before' },
      { label: "No, I've owned before", description: 'Previous homeownership experience' },
    ],
  },
  {
    id: 'timeline',
    emoji: '📅',
    title: 'When are you looking to buy?',
    type: 'choice',
    options: [
      { label: 'As soon as possible', description: 'Within the next 1–3 months' },
      { label: 'In the next 6 months', description: 'Actively searching' },
      { label: '6–12 months from now', description: 'Planning ahead' },
      { label: 'Just exploring', description: 'No timeline yet' },
    ],
  },
];

export const initialProfile: UserProfile = {
  employmentStatus: '',
  employmentLength: '',
  annualIncome: '',
  hasCoBorrower: '',
  coBorrowerIncome: '',
  creditScore: '',
  downPayment: '',
  monthlyDebt: '',
  mortgageType: '',
  propertyUse: '',
  propertyType: '',
  state: '',
  firstTimeBuyer: '',
  timeline: '',
  bankruptcyForeclosure: '',
};
