name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
    
    - name: Build the Docker image
      run: docker build ./WestleyIdea --file WestleyIdea/Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/mortgageai:latest

    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/mortgageai:latest
